# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions



name: 步步寶

on:
  workflow_dispatch:
  # 目前运行3000金币左右上限，body不用抓太多没有意义,cron自己看着写
  schedule:
     - cron: '0 8-23/2 * * *'
  watch:
    types: started
jobs:
  build:
    env:
      BBB_COOKIE: ${{ secrets.BBB_COOKIE }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install

      - name: '运行 【步步寶】'
        if: env.RONGHUA_VIDEO
        run: |
          node BBB.js
        env:
          BBB_COOKIE: ${{ secrets.BBB_COOKIE }}
